
spring.application.name=NammaKadai
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.nilctlyecnpwncstvjmm&password=Kavinkishore%406236&sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.nilctlyecnpwncstvjmm
spring.datasource.password=Kavinkishore@6236
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jmx.enabled=false

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=rkavinkishore@gmail.com
spring.mail.password=wtjt gvhc bfxi qtlr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000